regexes = [
    "Mod '(?<mod>.+)' \\(.+\\) .+ requires any version between .+ and .+ of (?<dep>.+), which is missing!",
    "Mod '(?<mod>.+)' \\(.+\\) .+ requires version .+ or later of (?<dep>.+), which is missing!",
]
severity = "High"
title = "Issue: Dependency missing"
response = """A dependency for {mod}, is missing.
Solution: Install a mod called `{dep}`."""
